---
steps:
  - label: "Julia {{ matrix.version }}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{ matrix.version }}"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
    agents:
      queue: "juliaecosystem"
      sandbox.jl: "true"
      os: "linux"
      arch: "x86_64"
    parallelism: 8
    timeout_in_minutes: 60
    matrix:
      setup:
        version:
          - "1.6"
          - "1.7"
          - "1.8"
          - "1.9"
          - "1"
          - "nightly"
      adjustments:
        - with:
            version: "nightly"
          soft_fail: true
