---
steps:
  - label: "Julia 1 - Test LinuxPerf Integration"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "x86_64"
    timeout_in_minutes: 15
