---
steps:
  branches: "master"
  label: "Julia {{ matrix.version }} - {{ github.event_name }}"
  plugins:
    - JuliaCI/julia#v1:
        version: "{{ matrix.version }}"
    - JuliaCI/julia-test#v1:
    - JuliaCI/julia-coverage#v1:
  agents:
    queue: "juliaecosystem"
    sandbox.jl: "true"
    os: "linux"
    arch: "x86_64"
  timeout_in_minutes: 60
  matrix:
    setup:
      version:
        - "1.0"
        - "1.5"
        - "1.6"
        - "1.7"
        - "1.8"
        - "1.9"
        - "1"
        - "nightly"
    adjustments:
      - with:
          version: "nightly"
        soft_fail: true
