name: Format suggestions
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@d758beeb6b381459ef1254656f351627155a0f0a # v4.1.0
        with:
          version: '1'