name: Format suggestions
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@cde9661e440a6a214c9c0c2c63a3dbdaa5fabd2f # v4.2.0
        with:
          version: '1'